sudo: true
language: node_js
install: npm install
compiler:
  - gcc
  - clang
env:
  - CXX=g++-4.8
addons:
  code_climate:
    repo_token: 04ba58c9679f5e0c72d45403383e9d0f353c89c3dd54aa60112083590a676602
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
node_js:
  - "node"
cache:
  directories:
    - node_modules
